project:
  type: website
  output-dir: docs

website:
  title: "Material Ataac 030_2025"
  navbar:
    left:
      - href: index.qmd
        text: "Início"
      - href: 01_aula.qmd
        text: "Prova Didática"
      - href: 02_memorial_v3.qmd
        text: "Memorial Circunstaciado"
      - href: 03_pesquisa_v2.qmd
        text: "Projeto de Pesquisa"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: source

